---

- name: Install first packages
  become: true
  apt:        
    state: present
    name:
      - curl
      - gnupg2 
      - lsb-release
    autoclean: yes

- name: Install development tools
  become: true
  apt:    
    state: present
    name:
      - build-essential
      - cmake
      - git
      - python3-pip
      - python-rosdep
      - wget
      - python3-colcon-common-extensions
      - python3-vcstool

- name: pip self-update
  pip:
    name: pip
    state: latest

- name: Install multi python packages
  pip:
    state: latest
    name:
      - argcomplete
      - flake8
      - flake8-blind-except
      - flake8-builtins
      - flake8-class-newline
      - flake8-comprehensions
      - flake8-deprecated
      - flake8-docstrings
      - flake8-import-order
      - flake8-quotes
      - pytest-repeat
      - pytest-rerunfailures
      - pytest
      - pytest-cov
      - pytest-runner
      - setuptools
            
- name: Install Fast-RTPS and Cyclone DDS dependencies
  become: true
  apt:
    state: present
    install_recommends: no
    name:
      - libasio-dev
      - libtinyxml2-dev
      - libcunit1-dev
